# **Análise da Geração Distribuída no Brasil**
<font size="5">**Análise Estatística**</font>    
    
---
<p style='text-align: right;'> Por Henrique Leão </p>

##  **1. Considerações Iniciais**

O presente Notebook tem como finalidade explorar estatisticamente os DataFrames provenientes dos Scripts '1_Manipulando_Dados.py' e '2_Criando_DataFrames', dessa forma iniciando o estudo dos dados ao qual o projeto se propõe.

Essa parte do estudo contém:

* Análise das Distribuições de Frequências
* <font color=blue> Em desenvolvimento </font>
* <font color=blue> Em desenvolvimento </font>

In [1]:
import pandas as pd
import warnings
warnings.filterwarnings("ignore")

In [2]:
df_Base = pd.read_csv('../Output/DataFrame_Base.csv', sep = ';', encoding = 'utf-8')
df_Base.dtypes

Concessionaria                object
Sigla                         object
Codigo_GD                     object
Tipo_Consumidor               object
Classe_Consumo                object
Grupo_Tarifario               object
Municipio                     object
UF                            object
Regiao                        object
Tipo_Geracao                  object
Fonte_Geracao                 object
Porte_Geracao                 object
Pot_Instalada_kW             float64
Modalidade                    object
Unidades_Recebem_Creditos      int64
SubEstacao                    object
Data_Conexao                  object
Latitude_GD                   object
Longitude_GD                  object
Latitude_Sub                  object
Longitude_Sub                 object
ID_Classe                      int64
ID_Grupo                       int64
ID_UF                          int64
ID_Municipio                   int64
dtype: object

##  **2. Distribuição de Frequências**

In [3]:
def Dist_Freq(Parametro):
    frequencia_absoluta = df_Base[Parametro].value_counts()
    frequencia_percentual = (df_Base[Parametro].value_counts(normalize = True) * 100).round(2)
    distribuicao = pd.DataFrame({'Frequencia': frequencia_absoluta, 'Percentual (%)': frequencia_percentual})
    distribuicao.rename_axis(Parametro, axis = 'columns', inplace = True)
    return distribuicao

def Dist_Freq_2(Parametro_1, Parametro_2):
    frequencia_absoluta = df_Base.groupby([Parametro_1])[Parametro_2].value_counts()
    frequencia_percentual = (df_Base.groupby([Parametro_1])[Parametro_2].value_counts(normalize = True) * 100).round(2)
    distribuicao = pd.DataFrame({'Frequencia': frequencia_absoluta, 'Percentual (%)': frequencia_percentual})
    return distribuicao

In [4]:
Dist_Freq('Classe_Consumo')\
    .style.format({'Percentual (%)': '{:.2f}'})\
    .bar(subset = ['Percentual (%)'], color='lightgreen', height=50, width=60)

In [5]:
Dist_Freq_2('Classe_Consumo', 'Regiao')\
    .style.format({'Percentual (%)': '{:.2f}'})\
    .bar(subset = ['Percentual (%)'], color='lightgreen', height=50, width=60)

##  **3. xxxxxx**

In [6]:
df_Base.groupby(['UF']).agg({'Pot_Instalada_kW': ['mean', 'median', 'max', 'std']}).round(2)

              Pot_Instalada_kW
                          mean median     max     std
UF
AC                       11.35    7.0   625.0   22.31
AL                       11.81    6.0  1206.0   29.82
AM                       16.03    8.0  1250.0   48.59
AP                       14.78    7.9   712.0   36.95
BA                        9.36    5.0  5000.0   30.76
CE                       12.03    5.0  5000.0   66.39
DF                       16.87    5.0  3125.0   91.70
ES                       12.52    6.0  3492.0   40.74
GO                       13.15    5.0  4200.0   53.25
MA                       13.04    6.0  1100.0   35.90
MG                       11.66    5.0  5000.0   73.89
MS                       10.20    5.0  2400.0   29.69
MT                       14.25    7.0  5000.0   52.63
Não Informado            13.41    9.5    75.0   13.71
PA                       11.74    6.0  2205.0   29.28
PB                       12.63    6.0  1500.0   33.16
PE                       12.12    5.0  4800.0   50.99
PI                       10.76    6.0  3120.0   39.09
PR                       12.04    5.0  4900.0   31.29
RJ                        8.83    5.0  4900.0   47.95
RN                       10.57    5.0  3000.0   33.06
RO                       13.26    6.0  2094.4   52.59
RR                       22.55    8.0  4500.0  180.63
RS                        9.47    5.0  2500.0   22.84
SC                       12.48    5.0  2000.0   26.59
SE                       12.76    7.2  1000.0   26.35
SP                        8.73    4.6  5000.0   40.61
TO                        9.96    6.0  1050.0   26.85